const $ = id => document.getElementById(id);

const p = {
  entradaPacientes:{name:'Entrada dos pacientes',detail:'Ponto identificado pelo QR Code',image:'assets/entrada.jpeg',instruction:'Entre e siga para a recepção',arrow:'forward'},
  recepcao:{name:'Recepção',detail:'Balcão de Informações',image:'assets/recepcao.jpeg',instruction:'Siga em frente pelo corredor principal',arrow:'forward'},
  corredorPrincipal:{name:'Corredor principal',detail:'Acompanhe as faixas no piso',image:'assets/corredor-principal.jpeg',instruction:'Continue até os elevadores',arrow:'forward'},
  elevadorDescer:{name:'Elevadores — 1º piso',detail:'Acesso aos serviços no térreo',image:'assets/elevadores.jpeg',instruction:'Desça um andar até o térreo',arrow:'down'},
  elevadorSubir:{name:'Elevadores — 1º piso',detail:'Acesso à área administrativa',image:'assets/elevadores.jpeg',instruction:'Suba um andar',arrow:'up'},
  entradaServico:{name:'Entrada de Serviço',detail:'Ponto identificado pelo QR Code',image:'assets/entrada-servico.jpg',instruction:'Entre e siga pelo corredor de serviço',arrow:'forward'},
  corredorServico:{name:'Corredor da Entrada de Serviço',detail:'Passe pelas catracas e siga em frente',image:'assets/corredor-entrada-servico.jpeg',instruction:'Continue até o final do corredor',arrow:'forward'},
  juncaoFarmacia:{name:'Ponto de decisão da Farmácia',detail:'Primeiro acesso à esquerda',image:'assets/juncao-servicos.jpeg',instruction:'Vire no primeiro acesso à esquerda',arrow:'left'},
  acessoFarmacia:{name:'Siga até o balcão da Farmácia',detail:'Trecho final para a Farmácia',image:'assets/corredor-farmacia.jpeg',instruction:'Siga até o balcão da Farmácia',arrow:'forward'},
  juncaoEsquerda:{name:'Ponto de decisão dos serviços',detail:'Segundo acesso à esquerda',image:'assets/juncao-servicos.jpeg',instruction:'Vire na segunda à esquerda',arrow:'left'},
  juncaoDireita:{name:'Ponto de decisão dos serviços',detail:'Acesso à direita',image:'assets/juncao-servicos.jpeg',instruction:'Vire à direita',arrow:'right'},
  corredorEsquerdo:{name:'Corredor do CME, Anatomia Patológica e Engenharia Clínica/Manutenção de equipamentos hospitalares',detail:'Ramal esquerdo',image:'assets/corredor-farmacia.jpeg',instruction:'Siga pelo corredor até o destino',arrow:'left'},
  corredorDireito:{name:'Corredor administrativo e de apoio',detail:'Hotelaria, Nutrição, Almoxarifado e Manutenção',image:'assets/corredor-administrativo.jpeg',instruction:'Vire à direita e siga pelo corredor',arrow:'right'},
  corredorZeladoria:{name:'Corredor da Zeladoria',detail:'Trecho final para Achados e Perdidos',image:'assets/corredor-zeladoria.jpeg',instruction:'Continue até o balcão da Zeladoria',arrow:'forward'},
  entradaAdministrativa:{name:'Entrada Administrativa',detail:'Após subir um andar',image:'assets/entrada-administrativa.jpeg',instruction:'Entre e siga para a Manutenção Predial',arrow:'forward'},
  farmacia:{name:'Balcão da Farmácia',detail:'Destino final',image:'assets/farmacia-balcao.jpeg',instruction:'Você chegou à Farmácia',arrow:'arrival'},
  engenharia:{name:'Entrada da Engenharia Clínica',detail:'Manutenção de Equipamento Hospitalar',image:'assets/engenharia-clinica.jpeg',instruction:'Você chegou à Engenharia Clínica',arrow:'arrival'},
  cme:{name:'Entrada do CME',detail:'Central de Material e Esterilização',image:'assets/cme-entrada.jpeg',instruction:'Você chegou ao CME',arrow:'arrival'},
  achados:{name:'Zeladoria — Achados e Perdidos',detail:'Ponto de atendimento',image:'assets/achados-perdidos.jpeg',instruction:'Você chegou a Achados e Perdidos',arrow:'arrival'},
  almoxarifado:{name:'Entrada do Almoxarifado',detail:'Ponto de atendimento',image:'assets/almoxarifado.jpeg',instruction:'Você chegou ao Almoxarifado',arrow:'arrival'},
  manutencao:{name:'Entrada da Manutenção Predial',detail:'Setor de Manutenção',image:'assets/manutencao-predial.jpeg',instruction:'Você chegou à Manutenção Predial',arrow:'arrival'},
  nutricao:{name:'Divisão de Nutrição e Dietética',detail:'Ponto de atendimento',image:'assets/nutricao.jpeg',instruction:'Você chegou à Nutrição',arrow:'arrival'},
  hotelaria:{name:'Serviço de Hotelaria e Higiene',detail:'Ponto de atendimento',image:'assets/hotelaria-higiene.jpeg',instruction:'Você chegou ao Serviço de Hotelaria',arrow:'arrival'}
  ,origemSuperintendencia:{name:'Entrada Administrativa da Superintendência',detail:'Ponto identificado pelo QR Code',image:'assets/origem-superintendencia.jpeg',instruction:'Entre e siga pelo corredor',arrow:'forward'}
  ,corredorSuperintendencia:{name:'Corredor da Superintendência',detail:'Acesso aos elevadores no 3º piso',image:'assets/corredor-superintendencia.jpeg',instruction:'Siga até os elevadores',arrow:'forward'}
  ,elevadoresTerceiro:{name:'Elevadores — 3º piso',detail:'Deslocamento até o 1º andar',image:'assets/elevadores-terceiro-piso.jpeg',instruction:'Pegue o elevador e desça até o 1º andar',arrow:'down'}
  ,saidaElevadoresPrimeiro:{name:'Saída dos elevadores — 1º andar',detail:'Pacientes/serviço: direita; visitantes: esquerda',image:'assets/saida-elevadores-primeiro.jpeg',instruction:'Vire à direita nos elevadores de pacientes ou serviço; à esquerda no elevador de visitantes',arrow:'right'}
  ,corredorAnatomiaSuperintendencia:{name:'Corredor da Anatomia, CME e Engenharia Clínica',detail:'Trecho final no 1º andar',image:'assets/corredor-anatomia-superintendencia.jpeg',instruction:'Siga pelo corredor até a Engenharia Clínica',arrow:'forward'}
  ,engenhariaSuperintendencia:{name:'Entrada da Engenharia Clínica',detail:'Destino final',image:'assets/engenharia-superintendencia.jpeg',instruction:'Você chegou à Engenharia Clínica',arrow:'arrival'}
  ,qrAlmoxarifadoFundos:{name:'Almoxarifado — QR dos fundos',detail:'Origem identificada pelo QR Code',image:'assets/qr-almoxarifado-fundos.jpeg',instruction:'Saia do Almoxarifado e siga pelo corredor',arrow:'forward'}
  ,acessoCmeAnatomia:{name:'Acesso ao CME, Anatomia e Engenharia Clínica',detail:'Ponto intermediário após o Almoxarifado',image:'assets/acesso-cme-anatomia-engenharia.jpeg',instruction:'Continue em direção ao corredor da Anatomia',arrow:'forward'}
  ,corredorAnatomiaFundos:{name:'Corredor da Anatomia',detail:'Trecho final para a Engenharia Clínica',image:'assets/corredor-anatomia-fundos.jpeg',instruction:'Siga pelo corredor até a Engenharia Clínica',arrow:'forward'}
  ,engenhariaFundos:{name:'Entrada da Engenharia Clínica',detail:'Destino final',image:'assets/engenharia-fundos.jpeg',instruction:'Você chegou à Engenharia Clínica',arrow:'arrival'}
  ,elevadorServicoTerceiro:{name:'Elevadores da Entrada de Serviço',detail:'Subida até o 3º andar',image:'assets/elevadores.jpeg',instruction:'Pegue o elevador e siga para o terceiro andar',arrow:'up'}
  ,saidaElevadorManutencao:{name:'Saída do elevador — 3º andar',detail:'Primeiro acesso à direita',image:'assets/corredor-superintendencia.jpeg',instruction:'Vá em direção à saída e vire na primeira à direita',arrow:'right'}
};

const patientBase=[p.entradaPacientes,p.recepcao,p.corredorPrincipal];
const serviceBase=[p.entradaServico,p.corredorServico];
const supportFromPatient=[...patientBase,p.elevadorDescer,p.juncaoDireita,p.corredorDireito];
const destinations={
  farmacia:{name:'Farmácia',icon:'+',floor:'Térreo',routes:{'entrada-pacientes':[...patientBase,p.elevadorDescer,p.acessoFarmacia,p.farmacia],'entrada-servico':[...serviceBase,p.juncaoFarmacia,p.acessoFarmacia,p.farmacia]}},
  engenharia:{name:'Engenharia Clínica',icon:'EC',floor:'1º piso',routes:{'entrada-pacientes':[...patientBase,p.elevadorDescer,p.corredorEsquerdo,p.engenharia],'entrada-servico':[...serviceBase,p.juncaoEsquerda,p.corredorEsquerdo,p.engenharia],'entrada-administrativa-superintendencia':[p.origemSuperintendencia,p.corredorSuperintendencia,p.elevadoresTerceiro,p.saidaElevadoresPrimeiro,p.corredorAnatomiaSuperintendencia,p.engenhariaSuperintendencia],'fundos-caixa-dagua':[p.qrAlmoxarifadoFundos,p.acessoCmeAnatomia,p.corredorAnatomiaFundos,p.engenhariaFundos]}},
  cme:{name:'CME',icon:'CME',floor:'Térreo',routes:{'entrada-pacientes':[...patientBase,p.elevadorDescer,p.corredorEsquerdo,p.cme],'entrada-servico':[...serviceBase,p.juncaoEsquerda,p.corredorEsquerdo,p.cme]}},
  manutencao:{name:'Manutenção Predial',icon:'MP',floor:'3º piso',routes:{'entrada-pacientes':[...patientBase,p.elevadorSubir,p.entradaAdministrativa,p.manutencao],'entrada-servico':[...serviceBase,p.elevadorServicoTerceiro,p.saidaElevadorManutencao,p.manutencao]}},
  achados:{name:'Achados e Perdidos',icon:'AP',floor:'1º piso',routes:{'entrada-pacientes':[...patientBase,p.corredorZeladoria,p.achados],'entrada-servico':[...serviceBase,p.juncaoDireita,p.corredorZeladoria,p.achados]}},
  almoxarifado:{name:'Almoxarifado',icon:'AL',floor:'Térreo',routes:{'entrada-pacientes':[...supportFromPatient,p.almoxarifado],'entrada-servico':[...serviceBase,p.juncaoDireita,p.corredorDireito,p.almoxarifado]}},
  nutricao:{name:'Nutrição',icon:'NU',floor:'Térreo',routes:{'entrada-pacientes':[...supportFromPatient,p.nutricao],'entrada-servico':[...serviceBase,p.juncaoDireita,p.corredorDireito,p.nutricao]}},
  hotelaria:{name:'Serviço de Hotelaria',icon:'SH',floor:'Térreo',routes:{'entrada-pacientes':[...supportFromPatient,p.hotelaria],'entrada-servico':[...serviceBase,p.juncaoDireita,p.corredorDireito,p.hotelaria]}}
};

const params=new URLSearchParams(location.search);
const validOrigins=['entrada-pacientes','entrada-servico','entrada-administrativa-superintendencia','fundos-caixa-dagua'];
let origin=validOrigins.includes(params.get('origem'))?params.get('origem'):'entrada-servico';
let destinationKey='engenharia',route=[],step=0,stream=null,scanTimer=null,signatures=[],currentConfidence=0;
let stableCandidate=-1,stableFrames=0,recognitionLocked=false,manualTimer=null;
let guidanceTimer=null,wakeLock=null,lastGuidance='';

function originLabel(){return {'entrada-pacientes':'Entrada de Pacientes','entrada-servico':'Entrada de Serviço','entrada-administrativa-superintendencia':'Entrada Administrativa da Superintendência','fundos-caixa-dagua':'Fundos/Caixa d’Água — QR no Almoxarifado'}[origin]}
function refreshRoute(){let d=destinations[destinationKey];if(!d.routes[origin]){destinationKey=Object.keys(destinations).find(key=>destinations[key].routes[origin]);d=destinations[destinationKey]}route=d.routes[origin];step=0;$('originName').textContent=originLabel();$('originSelect').value=origin;$('selectedIcon').textContent=d.icon;$('selectedName').textContent=d.name;$('selectedMeta').textContent=`${d.floor} · ${originLabel()} · ${route.length} pontos`;document.querySelectorAll('[data-destination]').forEach(button=>{const available=Boolean(destinations[button.dataset.destination].routes[origin]);button.disabled=!available;button.classList.toggle('pending',!available);button.classList.toggle('selected',button.dataset.destination===destinationKey);button.querySelector('small').textContent=available?'Rota disponível':'Rota ainda não cadastrada'});renderRoute();loadSignatures()}
function renderRoute(){$('routeList').innerHTML=route.map((point,i)=>`<li><span class="route-number">${i+1}</span><div><strong>${point.name}</strong><small>${point.detail}</small></div></li>`).join('')}
function selectDestination(key){destinationKey=key;document.querySelectorAll('[data-destination]').forEach(b=>b.classList.toggle('selected',b.dataset.destination===key));refreshRoute();showOnly('routeView');window.scrollTo({top:0,behavior:'smooth'})}
function changeOrigin(value){origin=value;const next=new URL(location.href);next.searchParams.set('origem',origin);history.replaceState({},'',next);refreshRoute()}
function showOnly(id){['setupView','routeView','cameraView','arrivalView'].forEach(v=>$(v).hidden=v!==id)}
async function startCamera(){lastGuidance='';showOnly('cameraView');updateStep();$('camera').hidden=false;try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});$('camera').srcObject=stream;$('fallbackImage').hidden=true;await $('camera').play();await keepScreenAwake();speakInstruction(`Navegação iniciada para ${destinations[destinationKey].name}. Aponte a câmera para o ambiente para confirmar sua localização.`);scanTimer=setInterval(analyzeFrame,650);guidanceTimer=setInterval(repeatGuidance,25000)}catch(e){$('camera').hidden=true;$('fallbackImage').hidden=false;$('recognitionStatus').textContent='Câmera indisponível — use o avanço manual';showManualFallback();speakInstruction('Não foi possível acessar a câmera. Use o avanço manual.')}}
function stopCamera(){if(scanTimer)clearInterval(scanTimer);if(manualTimer)clearTimeout(manualTimer);if(guidanceTimer)clearInterval(guidanceTimer);scanTimer=null;manualTimer=null;guidanceTimer=null;if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;if(wakeLock){wakeLock.release().catch(()=>{});wakeLock=null}window.speechSynthesis?.cancel()}
function updateStep(){const point=route[step];stableCandidate=-1;stableFrames=0;recognitionLocked=false;$('stepCount').textContent=`${step+1} de ${route.length}`;$('instruction').textContent='Aponte a câmera para o ambiente';$('locationLabel').textContent=`Procurando: ${point.detail}`;$('fallbackImage').src=point.image;$('arArrow').className=`ar-arrow ${point.arrow}`;$('recognitionStatus').textContent='Reconhecimento automático ativo…';$('confidence').textContent='';$('statusDot').className='status-dot';$('confirmBtn').hidden=true;currentConfidence=0;if(manualTimer)clearTimeout(manualTimer);manualTimer=setTimeout(showManualFallback,12000)}
function showManualFallback(){$('confirmBtn').hidden=false;$('confirmBtn').disabled=false;$('recognitionStatus').textContent='Ainda procurando o local…'}
function signatureFrom(source){const c=$('analysisCanvas'),ctx=c.getContext('2d',{willReadFrequently:true});c.width=32;c.height=24;ctx.drawImage(source,0,0,32,24);const d=ctx.getImageData(0,0,32,24).data,gray=[];for(let i=0;i<d.length;i+=4)gray.push((d[i]*.299+d[i+1]*.587+d[i+2]*.114)/255);const mean=gray.reduce((s,v)=>s+v,0)/gray.length;const variance=gray.reduce((s,v)=>s+(v-mean)**2,0)/gray.length;const sd=Math.sqrt(variance)||1;const out=gray.map(v=>(v-mean)/sd);for(let y=0;y<23;y+=2)for(let x=0;x<31;x+=2){const i=y*32+x;out.push(Math.abs(gray[i]-gray[i+1]),Math.abs(gray[i]-gray[i+32]))}return out}
function similarity(a,b){if(!a?.length||a.length!==b?.length)return 0;let sum=0;for(let i=0;i<a.length;i++){const x=a[i]-b[i];sum+=x*x}return Math.max(0,1-Math.sqrt(sum/a.length)/1.8)}
async function loadSignatures(){signatures=await Promise.all(route.map(point=>new Promise(resolve=>{const im=new Image();im.onload=()=>resolve(signatureFrom(im));im.onerror=()=>resolve([]);im.src=point.image})))}
function analyzeFrame(){const v=$('camera');if(recognitionLocked||v.readyState<2||!signatures.length)return;const frame=signatureFrom(v);let bestIndex=-1,bestScore=0;for(let i=step;i<signatures.length;i++){const score=similarity(frame,signatures[i]);if(score>bestScore){bestScore=score;bestIndex=i}}currentConfidence=Math.round(bestScore*100);$('confidence').textContent=`${currentConfidence}%`;if(bestScore>.76){if(stableCandidate===bestIndex)stableFrames++;else{stableCandidate=bestIndex;stableFrames=1}$('recognitionStatus').textContent=`Confirmando ${route[bestIndex].name}…`;if(stableFrames>=3){step=bestIndex;setRecognized()}}else{stableCandidate=-1;stableFrames=0;$('recognitionStatus').textContent=bestScore>.61?'Possível ponto — mantenha a câmera estável':'Procurando ponto de referência…'}}
function speakInstruction(text){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const speech=new SpeechSynthesisUtterance(text);speech.lang='pt-BR';speech.rate=.92;speech.pitch=1;speech.volume=1;window.speechSynthesis.speak(speech)}
function repeatGuidance(){if(lastGuidance&&!recognitionLocked)speakInstruction(`Continue seguindo a orientação: ${lastGuidance}. No próximo ponto de decisão, retire o celular e aponte a câmera para o ambiente.`)}
async function keepScreenAwake(){if(!('wakeLock'in navigator))return;try{wakeLock=await navigator.wakeLock.request('screen')}catch(e){wakeLock=null}}
function setRecognized(){recognitionLocked=true;if(manualTimer)clearTimeout(manualTimer);const point=route[step],arrived=point.arrow==='arrival';$('recognitionStatus').textContent=arrived?'Destino reconhecido automaticamente':'Local reconhecido automaticamente';$('statusDot').className='status-dot ready';$('confidence').textContent=`${Math.max(currentConfidence,86)}%`;$('instruction').textContent=point.instruction;$('locationLabel').textContent=point.name;$('confirmBtn').hidden=true;if(!arrived)$('arArrow').classList.add('visible');navigator.vibrate?.(arrived?[300,120,300]:[180,100,180]);lastGuidance=point.instruction;const spoken=arrived?point.instruction:`${point.instruction}. Você pode guardar o celular enquanto caminha. No próximo ponto de decisão, retire o celular e aponte a câmera para o ambiente.`;speakInstruction(spoken);setTimeout(nextStep,arrived?2800:5500)}
function nextStep(){if(step<route.length-1){step++;updateStep()}else{const d=destinations[destinationKey];stopCamera();$('arrivalTitle').textContent=`Você chegou: ${d.name}`;$('arrivalText').textContent=`O ponto de chegada de ${d.name} foi reconhecido. O percurso iniciado em ${originLabel()} está concluído.`;showOnly('arrivalView')}}
function openReference(){const point=route[step];$('referenceTitle').textContent=point.name;$('referencePhoto').src=point.image;$('referenceHint').textContent=point.detail;$('referenceDialog').showModal()}
async function toggleFlash(){const track=stream?.getVideoTracks()[0],cap=track?.getCapabilities?.();if(!cap?.torch)return;const on=!track._torch;await track.applyConstraints({advanced:[{torch:on}]});track._torch=on}

$('startBtn').onclick=startCamera;$('backToMenuBtn').onclick=()=>{showOnly('setupView');window.scrollTo({top:0,behavior:'smooth'})};$('closeBtn').onclick=()=>{stopCamera();showOnly('routeView');window.scrollTo({top:0,behavior:'smooth'})};$('confirmBtn').onclick=nextStep;$('referenceBtn').onclick=openReference;$('flashBtn').onclick=toggleFlash;$('restartBtn').onclick=()=>{step=0;showOnly('setupView');window.scrollTo({top:0,behavior:'smooth'})};$('helpBtn').onclick=()=>$('helpDialog').showModal();$('originSelect').onchange=e=>changeOrigin(e.target.value);document.querySelectorAll('.dialog-close').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('[data-destination]').forEach(b=>b.onclick=()=>selectDestination(b.dataset.destination));
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&stream&&!wakeLock)keepScreenAwake()});
refreshRoute();
